extern const GeoLayout surfboard_geo[];
extern u8 surfboard_RAINBOW_TEXTURE_ci8[];
extern u8 surfboard_RAINBOW_TEXTURE_ci8_pal_rgba16[];
extern Vtx surfboard_Surfboard_mesh_layer_1_vtx_cull[8];
extern Vtx surfboard_Surfboard_mesh_layer_1_vtx_0[45];
extern Gfx surfboard_Surfboard_mesh_layer_1_tri_0[];
extern Vtx surfboard_Surfboard_mesh_layer_1_vtx_1[27];
extern Gfx surfboard_Surfboard_mesh_layer_1_tri_1[];
extern Gfx mat_surfboard_surfboard_main[];
extern Gfx mat_revert_surfboard_surfboard_main[];
extern Gfx mat_surfboard_surfboard_tail[];
extern Gfx surfboard_Surfboard_mesh_layer_1[];
extern Gfx surfboard_material_revert_render_settings[];
