extern const GeoLayout hmc_area_1_geo[];
extern const GeoLayout hmc_area_1[];
extern const Collision hmc_area_1_collision[];
extern const MacroObject hmc_area_1_macro_objs[];
extern const GeoLayout hmc_area_2_geo[];
extern const GeoLayout hmc_dl_room_0_geo[];
extern const GeoLayout hmc_dl_room_1_geo[];
extern const GeoLayout hmc_dl_room_2_geo[];
extern const GeoLayout hmc_area_2[];
extern const Collision hmc_area_2_collision[];
extern const u8 hmc_area_2_collision_rooms[];
extern const MacroObject hmc_area_2_macro_objs[];
extern u8 hmc_dl_BigTreeWoodB_64x64_ci4_ci4[];
extern u8 hmc_dl_BigTreeWoodB_64x64_ci4_ci4_pal_rgba16[];
extern u8 hmc_dl_apartments_5_doors_ci4[];
extern u8 hmc_dl_apartments_5_doors_ci4_pal_rgba16[];
extern u8 hmc_dl_Glover_DE7624D3_0_0_8F915A34_ciByRGBA_ci4[];
extern u8 hmc_dl_Glover_DE7624D3_0_0_8F915A34_ciByRGBA_ci4_pal_rgba16[];
extern u8 hmc_dl_apartments_5_doors_2_ci4[];
extern u8 hmc_dl_apartments_5_doors_2_ci4_pal_rgba16[];
extern u8 hmc_dl_yuka_64x64_ci4_ci4[];
extern u8 hmc_dl_yuka_64x64_ci4_ci4_pal_rgba16[];
extern u8 hmc_dl__329B08FD44F137CC65EF2A6CFE0DB3CB_ci4[];
extern u8 hmc_dl__329B08FD44F137CC65EF2A6CFE0DB3CB_ci4_pal_rgba16[];
extern u8 hmc_dl_wise2_i4[];
extern u8 hmc_dl_kazeBright_i4[];
extern u8 hmc_dl_wc_isi_yellowish_64x64_ci4_ci4[];
extern u8 hmc_dl_wc_isi_yellowish_64x64_ci4_ci4_pal_rgba16[];
extern Vtx hmc_dl_beach_chair_visual_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_beach_chair_visual_mesh_layer_1_vtx_0[260];
extern Gfx hmc_dl_beach_chair_visual_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_Floor_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_Floor_mesh_layer_1_vtx_0[42];
extern Gfx hmc_dl_Floor_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_Floor_mesh_layer_1_vtx_1[12];
extern Gfx hmc_dl_Floor_mesh_layer_1_tri_1[];
extern Vtx hmc_dl_Floor_mesh_layer_1_vtx_2[10];
extern Gfx hmc_dl_Floor_mesh_layer_1_tri_2[];
extern Vtx hmc_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_Plane_mesh_layer_1_vtx_0[393];
extern Gfx hmc_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_Plane_mesh_layer_1_vtx_1[6];
extern Gfx hmc_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx hmc_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_Plane_001_mesh_layer_1_vtx_0[24];
extern Gfx hmc_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_UmbrellaPole_001_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_UmbrellaPole_001_mesh_layer_1_vtx_0[4];
extern Gfx hmc_dl_UmbrellaPole_001_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_UmbrellaPole_002_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_UmbrellaPole_002_mesh_layer_1_vtx_0[4];
extern Gfx hmc_dl_UmbrellaPole_002_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_UmbrellaTop_001_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_UmbrellaTop_001_mesh_layer_1_vtx_0[9];
extern Gfx hmc_dl_UmbrellaTop_001_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_UmbrellaTop_002_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_UmbrellaTop_002_mesh_layer_1_vtx_0[9];
extern Gfx hmc_dl_UmbrellaTop_002_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_Z_Water_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_Z_Water_mesh_layer_1_vtx_0[16];
extern Gfx hmc_dl_Z_Water_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_Z_Water_mesh_layer_5_vtx_cull[8];
extern Vtx hmc_dl_Z_Water_mesh_layer_5_vtx_0[38];
extern Gfx hmc_dl_Z_Water_mesh_layer_5_tri_0[];
extern Vtx hmc_dl_AAAAAAWalls_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_AAAAAAWalls_mesh_layer_1_vtx_0[540];
extern Gfx hmc_dl_AAAAAAWalls_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_AAAAAcave_door_visual_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_AAAAAcave_door_visual_mesh_layer_1_vtx_0[6];
extern Gfx hmc_dl_AAAAAcave_door_visual_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_Cave_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_Cave_mesh_layer_1_vtx_0[578];
extern Gfx hmc_dl_Cave_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_Cave_mesh_layer_1_vtx_1[119];
extern Gfx hmc_dl_Cave_mesh_layer_1_tri_1[];
extern Vtx hmc_dl_Cave_mesh_layer_1_vtx_2[3];
extern Gfx hmc_dl_Cave_mesh_layer_1_tri_2[];
extern Vtx hmc_dl_tunnel_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_tunnel_mesh_layer_1_vtx_0[42];
extern Gfx hmc_dl_tunnel_mesh_layer_1_tri_0[];
extern Gfx mat_hmc_dl_wood[];
extern Gfx mat_revert_hmc_dl_wood[];
extern Gfx mat_hmc_dl_hotel_wall[];
extern Gfx mat_revert_hmc_dl_hotel_wall[];
extern Gfx mat_hmc_dl_Sand[];
extern Gfx mat_revert_hmc_dl_Sand[];
extern Gfx mat_hmc_dl_hotel_door[];
extern Gfx mat_revert_hmc_dl_hotel_door[];
extern Gfx mat_hmc_dl_rock[];
extern Gfx mat_revert_hmc_dl_rock[];
extern Gfx mat_hmc_dl_warp[];
extern Gfx mat_revert_hmc_dl_warp[];
extern Gfx mat_hmc_dl_waterfall[];
extern Gfx mat_revert_hmc_dl_waterfall[];
extern Gfx mat_hmc_dl_pole[];
extern Gfx mat_hmc_dl_umbrella[];
extern Gfx mat_revert_hmc_dl_umbrella[];
extern Gfx mat_hmc_dl_waterOpaque_layer1[];
extern Gfx mat_revert_hmc_dl_waterOpaque_layer1[];
extern Gfx mat_hmc_dl_waterTransparent_layer5[];
extern Gfx mat_revert_hmc_dl_waterTransparent_layer5[];
extern Gfx mat_hmc_dl_rock_background_layer1[];
extern Gfx mat_revert_hmc_dl_rock_background_layer1[];
extern Gfx mat_hmc_dl_white_warp_layer1[];
extern Gfx mat_revert_hmc_dl_white_warp_layer1[];
extern Gfx mat_hmc_dl_rock_floor[];
extern Gfx mat_revert_hmc_dl_rock_floor[];
extern Gfx hmc_dl_beach_chair_visual_mesh_layer_1[];
extern Gfx hmc_dl_Floor_mesh_layer_1[];
extern Gfx hmc_dl_Plane_mesh_layer_1[];
extern Gfx hmc_dl_Plane_001_mesh_layer_1[];
extern Gfx hmc_dl_UmbrellaPole_001_mesh_layer_1[];
extern Gfx hmc_dl_UmbrellaPole_002_mesh_layer_1[];
extern Gfx hmc_dl_UmbrellaTop_001_mesh_layer_1[];
extern Gfx hmc_dl_UmbrellaTop_002_mesh_layer_1[];
extern Gfx hmc_dl_Z_Water_mesh_layer_1[];
extern Gfx hmc_dl_Z_Water_mesh_layer_5[];
extern Gfx hmc_dl_AAAAAAWalls_mesh_layer_1[];
extern Gfx hmc_dl_AAAAAcave_door_visual_mesh_layer_1[];
extern Gfx hmc_dl_Cave_mesh_layer_1[];
extern Gfx hmc_dl_tunnel_mesh_layer_1[];
extern Gfx hmc_dl_material_revert_render_settings[];
