extern const GeoLayout reonus_pfp_geo[];
extern u8 reonus_pfp_reonu_downscaled_up_rgba16[];
extern u8 reonus_pfp_reonu_downscaled_down_rgba16[];
extern Vtx reonus_pfp_reonus_pfp_mesh_layer_4_vtx_cull[8];
extern Vtx reonus_pfp_reonus_pfp_mesh_layer_4_vtx_0[4];
extern Gfx reonus_pfp_reonus_pfp_mesh_layer_4_tri_0[];
extern Vtx reonus_pfp_reonus_pfp_mesh_layer_4_vtx_1[4];
extern Gfx reonus_pfp_reonus_pfp_mesh_layer_4_tri_1[];
extern Gfx mat_reonus_pfp_reonus_pfp_layer4[];
extern Gfx mat_revert_reonus_pfp_reonus_pfp_layer4[];
extern Gfx mat_reonus_pfp_reonus_pfp_down_layer4[];
extern Gfx mat_revert_reonus_pfp_reonus_pfp_down_layer4[];
extern Gfx reonus_pfp_reonus_pfp_mesh_layer_4[];
extern Gfx reonus_pfp_material_revert_render_settings[];
